# -*- coding: utf-8 -*-
"""myencryptfile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onLPxZOaFFpi2fZJIRLirXtD8-MPGpQH
"""

import rsa

def encode_message(message):

    encoding_map = {
        'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10,
        'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19,
        't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, '.': 27, ' ': 28,
        ',': 29, '!': 30, '?': 31
    }

    return [encoding_map[char] for char in message.lower()]
def rsa_encrypt(plaintext, public_key, n):
    # Convert the plaintext into an integer
    plaintext_int = int.from_bytes(plaintext.encode('utf-8'), byteorder='big')

    # Encrypt the plaintext using the public key
    ciphertext = pow(plaintext_int, public_key, n)
    return ciphertext


# Given public key (n, e)
public_key = (1271, 17)

# Message to encrypt
message = "Wonderful class. A rating of eight out of ten. There could be less work given for an improvement"

# Encode the message
encoded_message = encode_message(message)
print("Encoded Message:",encoded_message)

# Encrypt the encoded message using RSA
encrypted_message = rsa_encrypt(encoded_message, public_key)
print("Encrypted Message:",encrypted_message)